---
- name: Deploy Bublik PR preview
  hosts: preview_server
  become: true
  vars:
    pr_id: 1

    traefik_domain: 'example.com'
    docker_repo: 'https://github.com/ts-factory/bublik-docker'
    docker_branch: 'main'

    frontend_repo: 'https://github.com/ts-factory/bublik-ui.git'
    frontend_branch: 'main'

    backend_repo: 'https://github.com/ts-factory/bublik.git'
    backend_branch: 'main'

  tasks:
    - include_role:
        name: preview-server
        tasks_from: deploy.yml
